version: '3.3'

services:
  backend:
    image: ae86jack/django-realworld-example-app
    build:
      context: .
      dockerfile: Dockerfile
    command: gunicorn conduit.wsgi:application -b 0.0.0.0:80
    depends_on:
      - db
    environment:
      SECRET_KEY: changeme
      DEBUG: 0
      DB_ENGINE: django.db.backends.postgresql
      DB_DATABASE: conduit
      DB_USER: postgres
      DB_PASSWORD: pwd
      DB_HOST: db
      DB_PORT: 5432
    labels:
      traefik.enable: "true"
      traefik.frontend.rule: PathPrefix:/api,/admin
      traefik.port: '80'
      traefik.tags: conduit.com
    volumes:
    - ./conduit:/app/conduit:rw
    networks:
      default:
        aliases:
          - localhost

  db:
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_DB: conduit
      POSTGRES_PASSWORD: pwd
      POSTGRES_USER: postgres
    image: postgres:11

  pgadmin:
    depends_on:
      - db
    environment:
      PGADMIN_DEFAULT_EMAIL: admin
      PGADMIN_DEFAULT_PASSWORD: pwd
      PGADMIN_LISTEN_PORT: '5050'
    image: dpage/pgadmin4
    ports:
      - published: 5050
        target: 5050

  frontend:
    image: ae86jack/vue-realworld-example-app
    build:
      context: ../vue-realworld-example-app   # Please set as the actual path of your vue project
    labels:
      traefik.enable: "true"
      traefik.frontend.rule: PathPrefix:/
      traefik.port: '80'
      traefik.tags: conduit.com

  proxy:
    command: --docker \ --docker.watch \ --docker.exposedbydefault=false \ --constraints=tag==conduit.com
      \ --logLevel=DEBUG \ --accessLog \ --web
    image: traefik:v1.7
    labels:
      traefik.enable: "true"
      traefik.frontend.rule: Host:localhost
      traefik.port: '80'
    ports:
      - published: 80
        target: 80
      - published: 8090
        target: 8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:rw
